name: twh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter 

  firebase_core: ^2.24.2
  firebase_storage: ^11.0.4
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.1
  http: ^0.13.5
  lottie: ^2.6.0
  excel: ^2.0.6
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  csv: ^5.0.2
  connectivity_plus: ^5.0.2
  pdf: ^3.11.3
  printing: ^5.11.0
  mime: ^1.0.4
  http_parser: ^4.0.2
  # path_provider: ^2.0.15
  share_plus: ^7.2.1
  flutter_local_notifications: ^9.0.0
  intl: ^0.18.1
  # permission_handler: ^10.2.0



  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/massage-chair.png
    - assets/assets/loading.json
    - assets/fonts/Cairo-Regular.ttf
    - assets/fonts/Cairo-Bold.ttf
